### PR TITLE
Allow for a custom resolver

### PR DESCRIPTION
**Pull request by x-yuri**
Reasoning. I'd like paths to be relative to project root, app root (in case of Django), or front end root. Make paths to project files distinguishable from paths to library files. And for all that be consistent across js, css, sass. While it might be a questionable idea, I start paths to project files with `/`. Now that I think about it, starting them with `~/` might be a better idea. Anyways, with native `path.resolve` that obviously doesn't work. With this PR I can resolve the issue this way:

```js
      loader: 'sass-loader',
      options: {
        importer: jsonImporter,
        resolver: (dir, url) => {
            // allow paths relative to front-end dir, starting with /
            if (url.startsWith('/')
            && c.insideDir(path.join(dir, 'filename'),
                path.join(root, 'front-end'))) {
                    return path.join(root, 'front-end', url.substr(1));
            }
            return path.resolve(dir, url);
        },
      },
```

Should I bump the version and add an entry to changelog?

### CODE REVIEW

**Comment by pmowrer** [comment]
Not sure I follow the problem you're experiencing... how are you using `node-sass`? I would imagine, for most users of this library, usually a build tool like `gulp` or `webpack` would be feeding the paths (using their path format)?

**Comment by x-yuri** [comment]
@pmowrer I want to have in `sass` `@import /vars`, and it being resolved relative to some predetermined dir. Or `@import ~/vars`. This PR allows me to do that.

**Comment by x-yuri** [comment]
@pmowrer In addition I had to add [another][cli.js] js file, to make it work from cli.

Speaking of which, right now it imports `./node-sass-json-importer` which doesn't exist in `src` dir. That's to make it work from `dist` dir. Can we make `babel` output its result to `dist/index.js`? This package is not going to be used in browser environment. But that would resolve the issue just mentioned. And would simplify `compile` command:

```diff
-babel -o dist/node-sass-json-importer.js src/index.js && babel -o dist/cli.js src/cli.js
+babel -d dist src/*.js
```

[cli.js]: https://github.com/Updater/node-sass-json-importer/blob/016a6a4d48d8e673e6690291a13d00edc1e2fa15/src/cli.js

**Comment by pmowrer** [comment]
@x-yuri Sure, I think that makes sense!

**Comment by x-yuri** [comment]
@pmowrer Is there anything else to be done in this PR? Bump the version? Add entry to changelog?

**Comment by pmowrer** [comment]
@x-yuri Sorry, yes a CHANGELOG update would be super helpful. Merge and publish should just take a minute then

**Comment by x-yuri** [comment]
@pmowrer Is this okay?

**Comment by pmowrer** [comment]
Thank you @x-yuri!

**Pull request merged**
